config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'ranking' => 'homes#ranking'
  get 'new' => 'homes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @post = Post.find(params[:post_id])
      #投稿に紐づいたコメントを作成
      @comment = @post.comments.new(comment_params)
      @comment.user_id = current_user.id
      @comment.save
end

    def destroy
      @comment = Comment.find(params[:id])
      #これ忘れると削除した後の読み込みができない
      @post = @comment.post
      if @comment.user != current_user
        redirect_to request.referer
      end
      @comment.destroy
    end

    private
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_count.html.slim
i.fa.fa-comment
  = post.comments.count

app/views/comments/_form.html.slim
= form_with model:[post, comment], url: post_comments_path(post) do |f|
  .comment__form
    = f.text_area :content, class: "comment__form__area"
    = f.submit "コメントする", class:"comment__form__submit font_theme_cyber"

app/views/comments/_index.html.slim
- post.comments.order(created_at: :desc).each do |comment|
  .comment
    - unless comment.id.nil?
      .profile__img
        = image_tag url_for(comment.user.image), class:"profile__img"
      .comment__cont
        .comment__txt
          = comment.content
      - if comment.user == current_user
          = link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true do
            i.fas.fa-trash-alt.destroy__btn.font_theme_cyber

app/views/comments/create.js.erb
$("#comment_<%= @post.id %>").html("<%= j(render 'comments/index', {post: @post }) %>")
$("#comment_count_<%= @post.id %>").html("<%= j(render 'comments/count', { post: @post}) %>");
$("textarea").val('');

app/views/comments/destroy.js.erb
$("#comment_<%= @post.id %>").html("<%= j(render 'comments/index', {post: @post }) %>")
$("#comment_count_<%= @post.id %>").html("<%= j(render 'comments/count', { post: @post}) %>");