config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'ranking' => 'homes#ranking'
  get 'new' => 'homes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  belongs_to :user, optional: true
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find_by(id: params[:user_id])
    current_user.follow(params[:user_id])
    # redirect_to request.referer
  end

  def destroy
    @user = User.find_by(id: params[:user_id])
    current_user.unfollow(params[:user_id])
    # redirect_to request.referer
  end

  def follower
    @user = User.find(params[:user_id])
    @users = @user.following_user
  end

  def followed
    @user = User.find(params[:user_id])
    @users = @user.follower_user
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.slim
- if current_user.following?(user)
  = link_to user_relationships_path(user), method: :delete, remote: true do
    .unfollow__btn.font_theme_cyber フォローはずす
- else
  = link_to user_relationships_path(user), method: :post, remote: true do
    .follow__btn.font_theme_cyber フォローする

app/views/relationships/_follow_count.html.slim
.follow__txt
    = link_to user_follows_path(user), class:"follow__link font_theme_cyber" do
      | フォロー
      = user.follower.size
    = link_to user_followers_path(user), class:"follow__link font_theme_cyber" do
      | フォロワー
      = user.followed.size

app/views/relationships/_follow_index.html.slim
main
  .container
    .row
      .user-index
        - @users.each do |user|
          .user-index__cont
                - if user.image.attached?
                  = link_to user_path(user) do
                    = image_tag url_for(user.image), class: "profile__img"
                = link_to user_path(user) do
                  p.user-index__name.txt_color_white
                    = user.name
                - if current_user != user
                 div id="user_follow_#{user.id}"
                  = render "relationships/follow", user: user
                - else
                  = link_to user_path(user) do
                    .unfollow__btn.font_theme_cyber mypage

app/views/relationships/create.js.erb
$("#post_follow_<%= @user.id %>").html("<%= j(render partial: 'relationships/follow', locals: { user: @user}) %>");
$("#post_follow2_<%= @user.id %>").html("<%= j(render partial: 'relationships/follow', locals: { user: @user}) %>");
$("#user_follow_<%= @user.id %>").html("<%= j(render partial: 'relationships/follow', locals: { user: @user}) %>");
$("#user_follow_count_<%= @user.id %>").html("<%= j(render partial: 'relationships/follow_count', locals: { user: @user}) %>");

app/views/relationships/destroy.js.erb
$("#post_follow_<%= @user.id %>").html("<%= j(render partial: 'relationships/follow', locals: {user: @user}) %>");
$("#post_follow2_<%= @user.id %>").html("<%= j(render partial: 'relationships/follow', locals: {user: @user}) %>");
$("#user_follow_<%= @user.id %>").html("<%= j(render partial: 'relationships/follow', locals: {user: @user}) %>");
$("#user_follow_count_<%= @user.id %>").html("<%= j(render partial: 'relationships/follow_count', locals: { user: @user}) %>");

app/views/relationships/followed.html.slim
= render "relationships/follow_index", users: @users

app/views/relationships/follower.html.slim
= render "relationships/follow_index", users: @users