config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'ranking' => 'homes#ranking'
  get 'new' => 'homes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :tag_posts, dependent: :destroy
  has_many :tags, through: :tag_posts
  enum age_limit: { 全年齢: 1, "R-18": 2, "R-18G": 3 }
  enum open_range: { 全体に公開: 1, フォロワーに公開: 2, 非公開: 3 }
  validates :title, presence: true
  validates :caption, presence: true
  validates :images, presence: true
  # タグを複数保存するメソッド
  def save_tag(tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: [:edit, :update, :destroy]
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    # スペースを入れることでタグを保存可能
    tag_list = params[:post][:name].split(nil)
    if @post.save
      # タグを複数保存する多対多を組み、メソッドをpostモデルに追加することでできる
      @post.save_tag(tag_list)
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    # 投稿に画像が存在して、かつ、選択した画像がある場合その画像を削除
    if @post.images.attached? && !params[:post][:image_ids].nil?
      params[:post][:image_ids].each do |image_id|
        image = @post.images.find(image_id)
        image.purge
      end
    end
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :caption, :age_limit, :open_range, images: [])
  end

  def screen_user
      @post = Post.find(params[:id])
      if @post.user.id != current_user.id
        redirect_to root_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_age_limit.html.slim
- if post.age_limit == "R-18"
  span.age-limit__badge R-18
- elsif post.age_limit == "R-18G"
  span.age-limit__badge R-18G

app/views/posts/edit.html.slim
= video_tag asset_path("top-video.mp4"), autoplay: :true, loop: :true, muted: :true, class: 'post__form__bg'
.post__wrap
  .container
    .row
      .post__form
          = form_with model: @post, url: post_path(@post), local: true do |f|
            = render "layouts/errors", obj: @post
            .field
              = f.label :images, class:"form__label"
              #image-box-1
                  .item-num-0#image-box__container
              label.form__image__label
                i.fa.fa-camera
                p.txt_size_xs 画像選択
                = f.file_field :images, class:"form__image", id:"img-file",multiple: true
              p 現在登録されている画像（削除するものはチェックしてください）
              .post__images__flex
                - @post.images.each do |image|
                  .post__images__cont
                    = f.check_box :image_ids, {:multiple => true}, image.id, false
                    = image_tag image, :size=>"100x100"
            .field
              = f.text_field :title, autofocus: true, autocomplete: "name",placeholder:"作品タイトル", class:"form__input"
              = f.text_area :caption, autofocus: true, autocomplete: "email",placeholder:"キャプション", class:"form__area"
            .field
                = f.label :name, class: "form__label"
                = f.text_field :name, class: "form__input"
            .field
              = f.label :age_limit, class:"form__label"
              - if current_user.over18?
                .form__radio
                  = f.radio_button :age_limit, :全年齢, checked: "checked"
                  = f.label :全年齢
                  = f.radio_button :age_limit, :"R-18"
                  = f.label :"R-18"
                  = f.radio_button :age_limit, :"R-18G"
                  = f.label :"R-18G"
              - else
                .form__radio
                  = f.radio_button :age_limit, :全年齢, checked: "checked"
                  = f.label :全年齢
                  = f.radio_button :age_limit, :"R-18", disabled: true
                  = f.label :"R-18"
                  = f.radio_button :age_limit, :"R-18G", disabled: true
                  = f.label :"R-18G"
            .field
              = f.label :open_range, class:"form__label"
              .form__radio
                = f.radio_button :open_range, :全体に公開, checked: "checked"
                = f.label :全体に公開
                = f.radio_button :open_range, :フォロワーに公開
                = f.label :フォロワーに公開
                = f.radio_button :open_range, :非公開
                = f.label :非公開
            .actions
              = f.submit "投稿する", class:"form__submit font_theme_cyber"
= javascript_include_tag 'post.js'

app/views/posts/index.html.slim
main
  .container
    .row
      .post
        .post-index
          .post__head__txt 検索結果
          b.hr.anim
          .post-index__cont
            - @search_posts.each do |post|
              .post__box
                = link_to post_path(post.id) do
                  /年齢制限表示
                  = render "posts/age_limit", post: post
                  /一枚目をサムネとして表示
                  - post.images.first(1).each do |image|
                    = image_tag url_for(image), class:"post__img"
                  p.post__title.bold = post.title
                  .post-user__cont
                    - if post.user.image.attached?
                        = image_tag url_for(post.user.image), class: "profile__img"
                        .post-user__txt.txt_color_white
                          = post.user.name

app/views/posts/new.html.slim
= video_tag asset_path("top-video.mp4"), autoplay: :true, loop: :true, muted: :true, class: 'post__form__bg'
.post__wrap
  .container
    .row
      .post__form
          = form_with model: @post, url: posts_path, local: true do |f|
            = render "layouts/errors", obj: @post
            .field
              = f.label :images, class:"form__label"
              #image-box-1
                  .item-num-0#image-box__container
              label.form__image__label
                i.fa.fa-camera
                p.txt_size_xs 画像選択
                = f.file_field :images, class:"form__image", id:"img-file",multiple: true
            .field
              = f.text_field :title, autofocus: true, autocomplete: "name",placeholder:"作品タイトル", class:"form__input"
              = f.text_area :caption, autofocus: true, autocomplete: "email",placeholder:"キャプション", class:"form__area"
            .field
                = f.label :name, class: "form__label"
                = f.text_field :name, class: "form__input"
            .field
              = f.label :age_limit, class:"form__label"
              - if current_user.over18?
                .form__radio
                  = f.radio_button :age_limit, :全年齢, checked: "checked"
                  = f.label :全年齢
                  = f.radio_button :age_limit, :"R-18"
                  = f.label :"R-18"
                  = f.radio_button :age_limit, :"R-18G"
                  = f.label :"R-18G"
              - else
                .form__radio
                  = f.radio_button :age_limit, :全年齢, checked: "checked"
                  = f.label :全年齢
                  = f.radio_button :age_limit, :"R-18", disabled: true
                  = f.label :"R-18"
                  = f.radio_button :age_limit, :"R-18G", disabled: true
                  = f.label :"R-18G"
            .field
              = f.label :open_range, class:"form__label"
              .form__radio
                = f.radio_button :open_range, :全体に公開, checked: "checked"
                = f.label :全体に公開
                = f.radio_button :open_range, :フォロワーに公開
                = f.label :フォロワーに公開
                = f.radio_button :open_range, :非公開
                = f.label :非公開
            .actions
              = f.submit "投稿する", class:"form__submit font_theme_cyber"
= javascript_include_tag 'post.js'

app/views/posts/show.html.slim
main
  .container
    .row
      .post.post-show
        .col-sm-9
          .post-show__cont
            - @post.images.each do |image|
              = image_tag url_for(image), class:"post__img"
            p.favorite.text-right id="favorite_#{@post.id}"
                    = render "likes/favorite",  {user: @user, post: @post}
            .detail
                p.title = @post.title
                p.caption = @post.caption
                p.favorite id="favorite_count_#{@post.id}"
                    = render "likes/favorite_count", post: @post
                p.favorite id="comment_count_#{@post.id}"
                    = render "comments/count", post: @post
                .tags
                  - @post.tags.each do |tag|
                    = link_to root_path, class:"tag__txt" do
                        | ##{tag.name}
                .post-user__cont2
                  - if @user.image.attached?
                    = link_to user_path(@user.id) do
                      = image_tag url_for(@user.image), class: "profile__img"
                    = link_to user_path(@user.id) do
                      p.post-user__name
                        = @user.name
                    - if current_user != @user
                      div id="post_follow2_#{@user.id}"
                        = render "relationships/follow", user: @user
                    - else
                      = link_to edit_post_path(@post.id) do
                        i.fas.fa-edit.edit__btn.font_theme_cyber
                      = link_to post_path(@post.id), method: :delete, data: { confirm: '本当に削除しますか？' } do
                        i.fas.fa-trash-alt.destroy__btn.font_theme_cyber
          = render "comments/form", {comment: @comment, post: @post}
          div id="comment_#{@post.id}"
              = render "comments/index", post: @post

        .col-sm-3.post-user__cont
              - if @user.image.attached?
                  = link_to user_path(@user.id) do
                    = image_tag url_for(@user.image), class: "profile__img"
                  = link_to user_path(@user.id) do
                    p.post-user__name
                      = @user.name
                  p.post-user__introduction
                    = @user.introduction
                  - if current_user != @user
                   div id="post_follow_#{@user.id}"
                    = render "relationships/follow", user: @user