config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'ranking' => 'homes#ranking'
  get 'new' => 'homes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  #一つの投稿に対して同じユーザーは一度しかいいねできない
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :tag_posts, dependent: :destroy
  has_many :tags, through: :tag_posts
  enum age_limit: { 全年齢: 1, "R-18": 2, "R-18G": 3 }
  enum open_range: { 全体に公開: 1, フォロワーに公開: 2, 非公開: 3 }
  validates :title, presence: true
  validates :caption, presence: true
  validates :images, presence: true
  # タグを複数保存するメソッド
  def save_tag(tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  belongs_to :user, optional: true
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_posts, dependent: :destroy
  has_many :posts, through: :tag_posts
end

app/models/tag_post.rb
class TagPost < ApplicationRecord
  belongs_to :tag
  belongs_to :post

  validates :post_id, presence: true
  validates :tag_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  has_many :relationships, dependent: :destroy
  validates :name, presence: true
  enum gender: { 男: 1, 女: 2, その他: 3 }

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  #既にいいねしているかどうか
 def already_liked?(post)
   self.likes.exists?(post_id: post.id)
 end

 def over18?
    d1=self.birth_date.strftime("%Y%m%d").to_i
    d2=Date.today.strftime("%Y%m%d").to_i
    age = (d2 - d1) / 10000
    age > 18
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @post = Post.find(params[:post_id])
      #投稿に紐づいたコメントを作成
      @comment = @post.comments.new(comment_params)
      @comment.user_id = current_user.id
      @comment.save
end

    def destroy
      @comment = Comment.find(params[:id])
      #これ忘れると削除した後の読み込みができない
      @post = @comment.post
      if @comment.user != current_user
        redirect_to request.referer
      end
      @comment.destroy
    end

    private
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def ranking
  end


  def new
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :post_params

  def create
      like = current_user.likes.new(post_id: @post.id)
      like.save
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: @post.id).destroy
  end

  private
  def post_params
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: [:edit, :update, :destroy]
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    # スペースを入れることでタグを保存可能
    tag_list = params[:post][:name].split(nil)
    if @post.save
      # タグを複数保存する多対多を組み、メソッドをpostモデルに追加することでできる
      @post.save_tag(tag_list)
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    # 投稿に画像が存在して、かつ、選択した画像がある場合その画像を削除
    if @post.images.attached? && !params[:post][:image_ids].nil?
      params[:post][:image_ids].each do |image_id|
        image = @post.images.find(image_id)
        image.purge
      end
    end
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :caption, :age_limit, :open_range, images: [])
  end

  def screen_user
      @post = Post.find(params[:id])
      if @post.user.id != current_user.id
        redirect_to root_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :screen_user, only: [:edit, :update]

  def follow

  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
      @user_posts = Post.where(user_id: @user)
    else
      @user_posts = @new_posts.where(user_id: @user)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def follower

  end

  def followed

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :introduction, :birth_date, :gender, :image)
  end

  def screen_user
      unless params[:id].to_i == current_user.id
        redirect_to user_path(current_user)
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.slim
/ - if obj.errors.any?
/   #error_explanation
/     ul
/       - obj.errors.full_messages.each do |message|
/         li.error__messages.txt_color_red
/            i.fa.fa-exclamation-triangle = message

app/views/layouts/_header.html.slim
= render 'search/search', q: @q
header
  .header__wrap
      .header__flex
        .header-left
          .logo
            = link_to root_path, data: {"turbolinks" => false} do
              = image_tag asset_path("logo_s.png"), class: "logo__img"
        .header-right
          .header-right__cont
            -if user_signed_in?
              = link_to new_post_path, class:"nav__txt" do
                  = image_tag asset_path("post.png"), class: "header__img"
              = link_to destroy_user_session_path, method: :delete,  class:"nav__txt" do
                  = image_tag asset_path("logout.png"), class: "header__img"
            -else
              = link_to user_session_path, class:"nav__txt" do
                  = image_tag asset_path("login.png"), class: "header__img"
              = link_to new_user_registration_path, class:"nav__txt" do
                  = image_tag asset_path("signup.png"), class: "header__img"
            a.btn.btn_theme_main data-target="#modal1" data-toggle="modal" type="button"
                i.fab.fa-searchengin.txt_color_white

          #nav
            #nav-toggle
              div
                span
                span
                span

            #gloval-nav
              nav.standard__txt
                ul
                  li
                        = link_to root_path, class:"nav__txt" do
                          = image_tag asset_path("home.png"), class: "nav__img"
                  li
                      = link_to ranking_path, class:"nav__txt" do
                        = image_tag asset_path("ranking.png"), class: "nav__img"
                  li
                      = link_to new_path, class:"nav__txt" do
                        = image_tag asset_path("new.png"), class: "nav__img"
                  li
                      = link_to root_path, class:"nav__txt" do
                        = image_tag asset_path("event.png"), class: "nav__img"
                  -if user_signed_in?
                    li
                        = link_to user_path(current_user), class:"nav__txt" do
                          = image_tag asset_path("mypage.png"), class: "nav__img"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CyberdrawApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" rel="stylesheet" type="text/css"
    link href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css" rel="stylesheet" type="text/css"
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
    script src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js" type="text/javascript"
    script src="https://kit.fontawesome.com/f3fffa880e.js" crossorigin="anonymous"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = javascript_include_tag "particles.min"

  body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/search/_search.html.slim
#modal1.modal.fade aria-hidden="true" aria-labelledby="label1" role="dialog" tabindex="-1"
     .modal-dialog role="document"
      .modal-content
        .modal-header
            button.close aria-label="Close" data-dismiss="modal" type="button"
                span aria-hidden="true"  ×
            h3#label1.modal-title.font_theme_cyber SEARCH
        .modal-body
                = search_form_for q, url: posts_path do |f|
                            .search
                                .field
                                    = f.label :title, 'タイトル・タグ',class:"form__label font_theme_cyber"
                                    = f.search_field :title_or_tags_name_cont,class:"form__item_input"
                                .field
                                    = f.label :age_limit,"ねんれいせいげん", class:"form__label font_theme_cyber"
                                    - if user_signed_in? && current_user.over18?
                                        .form__radio
                                            = f.radio_button :age_limit_eq, 1 , checked: "checked"
                                            = f.label :全年齢
                                            = f.radio_button :age_limit_eq, 2
                                            = f.label :"R-18"
                                            = f.radio_button :age_limit_eq, 3
                                            = f.label :"R-18G"
                                    - else
                                        .form__radio
                                            = f.radio_button :age_limit_eq, 1, checked: "checked"
                                            = f.label :全年齢
                                            = f.radio_button :age_limit_eq, 2, disabled: true
                                            = f.label :"R-18"
                                            = f.radio_button :age_limit_eq, 3, disabled: true
                                            = f.label :"R-18G"
                                .field
                                    = f.label :open_range,"こうかいはんい", class:"form__label font_theme_cyber"
                                    .form__radio
                                        = f.radio_button :open_range_eq, 1, checked: "checked"
                                        = f.label :全体に公開
                                        = f.radio_button :open_range_eq, 2
                                        = f.label :フォロワー限定
                                        = f.radio_button :open_range_eq, 3
                                        = f.label :非公開
                                .actions
                                    = f.submit "SEARCH", class:"form__submit font_theme_cyber"